smashmd:
	smashmd ./intro/demo/demo_core.md > ./intro/demo_dist/demo_core.md
	smashmd ./intro/demo/demo_chart.md > ./intro/demo_dist/demo_chart.md
	smashmd ./intro/demo/demo_brush.md > ./intro/demo_dist/demo_brush.md
	smashmd ./intro/demo/demo_tooltip.md > ./intro/demo_dist/demo_tooltip.md
	smashmd ./intro/demo/demo_zoom.md > ./intro/demo_dist/demo_zoom.md
	smashmd ./docs/basic/md_origin/line.md > ./docs/basic/md/line.md
	smashmd ./docs/basic/md_origin/line_multi.md > ./docs/basic/md/line_multi.md
	smashmd ./docs/basic/md_origin/area.md > ./docs/basic/md/area.md
	smashmd ./docs/basic/md_origin/area_stack.md > ./docs/basic/md/area_stack.md
	smashmd ./docs/basic/md_origin/bar.md > ./docs/basic/md/bar.md
	smashmd ./docs/basic/md_origin/bar_group.md > ./docs/basic/md/bar_group.md
	smashmd ./docs/basic/md_origin/bar_stack.md > ./docs/basic/md/bar_stack.md
	smashmd ./docs/basic/md_origin/donut.md > ./docs/basic/md/donut.md
	smashmd ./docs/basic/md_origin/pie.md > ./docs/basic/md/pie.md
	smashmd ./docs/basic/md_origin/scatter.md > ./docs/basic/md/scatter.md
	smashmd ./docs/core/md_origin/chart.md > ./docs/core/md/chart.md
	smashmd ./docs/core/md_origin/grid.md > ./docs/core/md/grid.md
	smashmd ./docs/core/md_origin/legend.md > ./docs/core/md/legend.md
	smashmd ./docs/core/md_origin/xaxis.md > ./docs/core/md/xaxis.md
	smashmd ./docs/core/md_origin/yaxis.md > ./docs/core/md/yaxis.md
